version: '3'
 
services:
  db:
    image: mysql:8.0.23
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=geheim"
      - "MYSQL_DATABASE=psvdb"
    ports:
      - "23306:3306"
    volumes:
      - ./dockerdata/entrypoint/:/docker-entrypoint-initdb.d/
      - ./dockerdata/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./startup.sh:/startup.sh
      - ./dbdata/:/var/lib/mysql/
    entrypoint: "/bin/bash"
    command: "/startup.sh"
volumes:
  dbdata: 
